[project]
name = "sinusoidal_analysis"
version = "0.1.0"
dependencies = ["numpy", "scipy"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools] 
py-modules = ["cli"]
packages = ["analyzers", "utils", "mixins"]
