[project]
name = "sinusoidal_analysis"
version = "0.1.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools] 
py-modules = ["cli"]
packages = ["analyzers", "utils", "mixins"]
